sudo: required
services:
  - docker

before_install:
  - docker build -t levmichael3/docker-frontend -f Dockerfile.Dev .

script:
  - docker run levmichael3/docker-frontend npm run test -- --coverage
