FROM node:alpine

# install node modules
WORKDIR   /app

ENV       PATH=/app/node_modules/.bin:$PATH

ADD       package.json /app/package.json
RUN       npm install  --ignore-scripts --unsafe-perm

COPY      . /app

CMD       ["npm", "run", "start"]
