sudo: required
services:
  - docker

before_install:
  - docker build -t testme -f Dockerfile.dev .

script:
  - docker run testme npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker_udemy"
  env: "frontend"
  bucket_name: "elasticbeanstalk-eu-west-1-501540795480"
  bucket_path: "docker_udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

notifications: # set notification options
  email:
    recipients:
      - levmichael3@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always
